In [2]:
import numpy as np
import pandas as pd


In [3]:
datafile= pd.read_csv(r"C:\Users\Manjula\Desktop\DataScienceAssignments\Csv_filesforDS/Social_Network_Ads.csv")

In [4]:
datafile.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
datafile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
# userid willnot be taken for consideration coz ML doesnt need any names/users to give the o/p
# here we take column 2,3 as independent variables(X). we can also use iloc

X= datafile.iloc[:,[2,3]].values                 # just taking all values of columns 2 and 3.. 

In [7]:
X[:5]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]], dtype=int64)

In [15]:
x= datafile[["Age","EstimatedSalary"]]
x[:3]                          # here we get x as df table. 

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000

In [14]:
x=  datafile[["Age","EstimatedSalary"]].values        # if we want it in array form then we use '.values'
x[:2]

array([[   19, 19000],
       [   35, 20000]], dtype=int64)

In [19]:
Y= datafile.iloc[:,4].values
Y                        # here we have 0,1 values in 4th column which we took as dependent variable

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [21]:
# splitting the data to training set and test set

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,Y, test_size=0.25, random_state=200)


In [22]:
X_train.shape

(300, 2)

In [23]:
Y_train.shape

(300,)

In [24]:
X_test.shape

(100, 2)

In [32]:
# we can see that X variable values are differing in huge range. hence we need preprocessing,ie bring both column values to 
# similar range. 
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X_train= sc_X.fit_transform(X_train)
X_test= sc_X.fit_transform(X_test)



In [33]:
X_train[:5]

array([[ 0.03016333, -0.22931642],
       [-0.06508929,  0.10229804],
       [ 0.98268949, -1.07342594],
       [-1.77963637,  0.49420603],
       [-1.01761545,  2.061838  ]])

In [34]:
X_test[:5]

array([[ 0.33035012, -0.6091173 ],
       [ 1.10084602, -1.2416093 ],
       [-0.15120982, -0.27912147],
       [ 1.96765391,  0.76586531],
       [ 0.42666211, -0.25162182]])

In [70]:
# fitting the model Classifier into the training set

from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=1500, criterion='entropy')  # n_estimators are number of decision trees
classifier.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1500)

In [71]:
# predicting test set result

Y_predict= classifier.predict(X_test)


In [72]:
# calculation of accuracy using the f1score

from sklearn.metrics import f1_score
f1_score(Y_test,Y_predict)

0.8157894736842106